### ISSUE TITLE
Health check using docker-compose

### ISSUE THREAD

**Issue by vab2048** [AxonIQ/axon-server-se#139]
Hi,

I have the following health check as part of my docker compose file:

```yml
version: '3.3'
services:
  axon-server:
    image: axoniq/axonserver:4.2.4-jdk11
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8024/v1/public"]
      interval: 30s
      timeout: 10s
      retries: 5
   # ports, hostname, environment not shown
```

After running `docker ps -a` we can see that docker is reporting that is healthy:

```sh
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                    PORTS
                                        NAMES
c485d540a2fd        axoniq/axonserver:4.2.4-jdk11   "/bin/sh -c ${AXONSE…"   42 seconds ago      Up 38 seconds (healthy)   0.0.0.0:8024->8024/tcp, 0.0.0.0:8124->8124/tcp, 0.0.0.0:8224->8224/tcp   deployments_axon-server_1
```

However, when we change the image to use the 'distroless' one: `image: axoniq/axonserver:4.3.3` the health check no longer works:

 ```sh
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                     PORTS
                                   NAMES
d00205554919        axoniq/axonserver:4.3.3   "java -cp /app/resou…"   3 minutes ago       Up 3 minutes (unhealthy)   0.0.0.0:8024->8024/tcp, 0.0.0.0:8124->8124/tcp, 0.0.0.0:8224->8224/tcp   deployments_axon-server_1
```

Is this because `curl` is not available in the container? What would be recommended approach to use the distroless image and provide a health check?
