### ISSUE TITLE
AxonServer Dashboard with access control enabled always redirects to HTTP

### ISSUE THREAD

**Issue by ViliusS** [AxonIQ/axon-server-se#501]
When running AxonServer Dashboard with access control enabled and behind HTTPS ingress loadbalancer the login form always redirects to HTTP.

For example if I run it under **https**://axon-dashboard.example.com  first initial redirect is always to **http**://axon-dashboard.example.com/login
Also, if I put **https**://axon-dashboard.example.com/login by hand and specify incorrect password it is also redirected to **http**://axon-dashboard.example.com/login?error

This makes dashboard inaccessible on ingress controllers where plain HTTP is disabled.

**Comment by MGathier** [comment]
Can you share your ingress configuration?  I don't see any redirect to HTTP on the Axon Server side. 
Which Axon Server version are you using?

**Comment by ViliusS** [comment]
I'm using Axon Server 4.5.12 and I jus rechecked on our different environment, it looks like the issue is only present in GCE ingress on Google Cloud. On-premises nginx-ingress controller doesn't have this issue. I guess this is because nginx-ingress forces redirect to SSL, but GCE doesn't.

Sample GCE ingress below:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "sample-static-ip"
    networking.gke.io/managed-certificates: "axon-saas-certificate,saas-certificate"
    # set to "true" when creating this ingress first time https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#disabling_http
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: axon-saas.example.com
    http:
      paths:
      - backend:
          service:
            name: axonserver-gui
            port:
              name: gui
        path: /
        pathType: Prefix
  - host: saas.example.com
    http:
      paths:
      - backend:
          service:
            name: eureka
            port:
              number: 8888
        path: /eureka
        pathType: Prefix
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix
```
